### ISSUE TITLE
Is Spectrum visualization running at 2160p when using Unlimited (4k) GUI resolution?

### ISSUE THREAD

**Issue by classicjazz** [xbmc/visualization.spectrum#10]
This is a cross-reference of this issue:
https://github.com/koying/SPMC/issues/403

I am running SPMC 16.5RC on Nvidia Shield TV v3.3 at unlimited (4k) resolution).

To my eyes, the bar graphs rendered by Spectrum visualization look fuzzy, like they are rendered at a much lower resolution. I would expect the corners to be crisp, like fonts are.

I took at a look at the code but cannot find anything that defines a specific resolution ceiling.

**Comment by akva2** [comment]
there is no such limiting, but i have no idea what resolution applies for spmc rendering controls. i suspect they will be upscaled indeed (repo owner, work identity).

**Comment by koying** [comment]
In "unlimited", on Shield, the GUI runs at 2160p.
It works fine for pictures and video, so I don't see why it would be different for viz, really...

@classicjazz A Kodi/SPMC screenshot should give you a 4K pic. It might be more obvious...
