### ISSUE TITLE
Fixed viewpoint (disable rotation)

### ISSUE THREAD

**Issue by kekukui** [xbmc/visualization.spectrum#23]
**I suggest a control which permits the viewer to choose a fixed viewpoint by input cardinal direction
(possibly 1-8 or 1-16)**

![bluemars](https://user-images.githubusercontent.com/20834957/52074743-934a9880-2558-11e9-981e-2d6dda3ee788.png)

**Comment by AlwinEsch** [comment]
Becomes added with https://github.com/xbmc/visualization.spectrum/pull/25

And then something like this possible:
![Bildschirmfoto von 2019-03-23 01-59-00](https://user-images.githubusercontent.com/6879739/54859596-64a69e00-4d0f-11e9-956b-c994e784a8dc.png)

with:
![Bildschirmfoto von 2019-03-23 01-59-17](https://user-images.githubusercontent.com/6879739/54859600-725c2380-4d0f-11e9-8b5f-dc71ab44784d.png)

**Comment by AlwinEsch** [comment]
Is in and now supported.
